name: Docker Image CI

env:
  IMAGE_NAME: flask-container-action
  IMAGE_TAG: latest

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:

  build:
    runs-on: ubuntu-16.04
    steps:
    - uses: actions/checkout@v2
    #- name: Build the Docker image
      #run: docker build . --file Dockerfile --tag '${{ IMAGE_NAME }}:latest'
      
    - uses: azure/docker-login@v1
      with:
        login-server: 'rcdemocontainerreg.azurecr.io' # default: index.docker.io
        username: ${{ secrets.ACR_USER }}
        password: ${{ secrets.ACR_PWD }}
    - run: |
        docker build . -t rcDemoContainerReg.azurecr.io/flask-container-action:${{ github.sha }}
        docker push rcDemoContainerReg.azurecr.io/flask-container-action:${{ github.sha }}
