name: Docker Image CI

env:
  IMAGE_NAME: flask-container-action
  IMAGE_TAG: latest

on:
  workflow_dispatch:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:

  build:
    runs-on: ubuntu-latest
    steps:
    - uses: azure/login@v1
      with:
        creds: ${{ secrets.AZ_CREDS }}
    
    - uses: actions/checkout@v2
    - uses: actions/setup-python@v2
      with:
        python-version: 3.8

    - run: pip install -r requirements.txt
    - run: pytest -vv

    - uses: azure/docker-login@v1
      with:
        login-server: rcdemoregistry.azurecr.io # default: index.docker.io
        username: ${{ secrets.REGISTRY_USERNAME }}
        password: ${{ secrets.REGISTRY_PASSWORD }}
    - run: |
        docker build . -t rcdemoregistry.azurecr.io/rcapps/flask-container-action:latest
        docker push rcdemoregistry.azurecr.io/rcapps/flask-container-action:latest
    
    - uses: azure/container-scan@v0
      with:
        image-name: rcdemoregistry.azurecr.io/rcapps/flask-container-action:latest # ${{ env.loginServerUrl }}/ would be empty if it's hosted on dockerhub; ${{ github.sha }} could also be replaced with any desired image tag
        username: ${{ secrets.REGISTRY_USERNAME }}
        password: ${{ secrets.REGISTRY_PASSWORD }}

    - name: 'Deploy to Azure Container Instances'
      uses: 'azure/aci-deploy@v1'
      with:
        resource-group: DevLab
        dns-name-label: flaskacidemo
        image: rcdemoregistry.azurecr.io/rcapps/flask-container-action:latest
        registry-login-server: rcdemoregistry.azurecr.io
        registry-username: ${{ secrets.REGISTRY_USERNAME }}
        registry-password: ${{ secrets.REGISTRY_PASSWORD }}
        name: democi
        location: 'east us2'
