name: Docker Image CI

env:
  IMAGE_NAME: flask-container-action
  IMAGE_TAG: latest

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]
  workflow_dispatch:

jobs:

  build:
    runs-on: ubuntu-latest
    steps:
    - uses: azure/login@v1
      with:
        creds: ${{ secrets.AZ_CREDS }}
    
    - uses: actions/checkout@v2
    - uses: actions/setup-python@v2
      with:
        python-version: 3.8
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt
      - name: Test with pytest
        run: pytest -vv
    #- name: Build the Docker image
      #run: docker build . --file Dockerfile --tag '${{ IMAGE_NAME }}:latest'

    
    - uses: azure/docker-login@v1
      with:
        login-server: rcdemoregistry.azurecr.io # default: index.docker.io
        username: ${{ secrets.REGISTRY_USERNAME }}
        password: ${{ secrets.REGISTRY_PASSWORD }}
    - run: |
        docker build . -t rcdemoregistry.azurecr.io/rcapps/flask-container-action:latest
        docker push rcdemoregistry.azurecr.io/rcapps/flask-container-action:latest

    - name: 'Deploy to Azure Container Instances'
      uses: 'azure/aci-deploy@v1'
      with:
        resource-group: DevLab
        dns-name-label: flaskacidemo
        image: rcdemoregistry.azurecr.io/rcapps/flask-container-action:latest
        registry-login-server: rcdemoregistry.azurecr.io
        registry-username: ${{ secrets.REGISTRY_USERNAME }}
        registry-password: ${{ secrets.REGISTRY_PASSWORD }}
        name: democi
        location: 'east us2'
